Repository MapChillE/uble-fe, pull requests merged in 2025-08, with the labels that each got.

#166 [HOTFIX] UBLE-143 바코드가 없어도 혜택 사용이 가능한 현상 수정
  apps/user/src/components/modal/BenefitConfirmModal.tsx
  apps/user/src/components/ui/BarcodeContainer.tsx
Labels: hotfix

#171 [FEAT] UBLE-148 관리자 로그인
  apps/admin/src/components/LoginPage.tsx
  apps/admin/src/service/login.ts
  apps/admin/src/types/responseStatus.ts
  apps/admin/src/types/user.ts
  apps/admin/tsconfig.json
Labels: enhancement, FE, admin

#168 [FEAT] UBLE-146 지도 검색창 최근 검색기록 구현 및 실시간 인기 검색어 마크업
  apps/user/src/app/(main)/home/components/SearchSection.tsx
  apps/user/src/app/(main)/map/components/MapSearchSection.tsx
  apps/user/src/app/(main)/search/components/RecentSearchesSection.tsx
  apps/user/src/app/(main)/search/components/SearchContainer.tsx
  apps/user/src/app/(main)/search/components/SearchSuggestionsSection.tsx
  apps/user/src/app/(main)/search/components/TrendingSearchesSection.tsx
  apps/user/src/components/common/AutoCompleteInput.tsx
  apps/user/src/components/common/SearchInput.tsx
  apps/user/src/hooks/useTrendingSearches.ts
  apps/user/src/service/trendingSearch.ts
  apps/user/src/store/useSearchStore.ts
Labels: enhancement, FE

#172 [FIX] UBLE-141 매장 상세 카드 즐겨찾기 동기화
  apps/user/src/components/FavoriteBtn.tsx
  apps/user/src/store/useStoreDetailDrawerStore.ts
Labels: enhancement, FE

#173 [FEAT] UBLE-147 지도 내 브랜드 필터링 구현
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/search/components/TrendingSearchesSection.tsx
  apps/user/src/components/common/BrandCard.tsx
  apps/user/src/components/common/BrandSelectionDrawer.tsx
  apps/user/src/components/common/OfflineBrandFilter.tsx
  apps/user/src/hooks/map/useCurrentLocation.ts
  apps/user/src/hooks/useOfflineBrands.ts
  apps/user/src/service/brand.ts
  packages/ui/src/components/button.tsx
Labels: enhancement, FE

#175 [REFACTOR] 지도 레이아웃 설정 및 폰트 설정
  apps/user/public/fonts/Futura-Bold.otf
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/components/common/Header.tsx
  packages/ui/src/styles/globals.css
Labels: enhancement, FE

#177 [FEAT] 실시간 인기 검색어 API 연동
  apps/user/src/app/(main)/search/components/RecentSearchesSection.tsx
  apps/user/src/app/(main)/search/components/TrendingSearchesSection.tsx
  apps/user/src/hooks/useTrendingSearches.ts
  apps/user/src/service/mapSearch.ts
  apps/user/src/service/trendingSearch.ts
  apps/user/src/types/search.ts
Labels: enhancement, FE

#178 [FEAT] UBLE-153 피드백 리스트 열람
  apps/admin/package.json
  apps/admin/src/app/(content)/feedback/components/FeedbackContainer.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackStatistics.tsx
  apps/admin/src/app/(content)/feedback/components/ui/FeedbackError.tsx
  apps/admin/src/app/(content)/feedback/components/ui/FeedbackSkeleton.tsx
  apps/admin/src/components/providers.tsx
  apps/admin/src/service/feedback.ts
  apps/admin/src/types/feedback.ts
  pnpm-lock.yaml
Labels: enhancement, FE, admin

#180 [FIX] useBaseLocation 파라미터 추가
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
Labels: bug, FE

#182 [Feat] UBLE-157 사용자 통계 조회
  apps/admin/src/app/(content)/statistics/components/ErrorState.tsx
  apps/admin/src/app/(content)/statistics/components/LoadingState.tsx
  apps/admin/src/app/(content)/statistics/components/RenderChart.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsChartContainer.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsContainer.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsFilter.tsx
  apps/admin/src/app/(content)/statistics/utils/chartDataTransformers.ts
  apps/admin/src/service/statistics.ts
  apps/admin/src/types/constants.ts
  apps/admin/src/types/rank.ts
  apps/admin/src/types/statistics.ts
Labels: enhancement, FE, admin

#183 [FEAT] UBLE-158 변경된 카테고리 적용 및 마커, 클러스터러 스타일 수정
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/components/SearchModeBtn.tsx
  apps/user/src/app/(main)/map/hooks/useMarkerAndClusterManager.ts
  apps/user/src/app/(main)/search/layout.tsx
  apps/user/src/components/common/CategoryBar.tsx
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/types/constants.ts
  apps/user/src/utils/categoryColor.ts
  apps/user/src/utils/fetchStorePins.ts
  packages/ui/src/components/button.tsx
  packages/ui/src/styles/globals.css
Labels: enhancement, FE

#185 [FIX] 배포환경에서 발생하는 문제(스타일) 해결
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/SearchModeBtn.tsx
  apps/user/src/utils/fetchStorePins.ts
Labels: bug, FE

#188 [FEAT] UBLE-160 middleware를 통하여 세션 존재 여부 검증
  apps/user/src/middleware.ts
Labels: enhancement, FE

#193 [HOTFIX] UBLE-162 matcher 경로 수정
  apps/user/src/middleware.ts
Labels: hotfix

#195 [HOTFIX] UBLE-162 실제 사용 경로만 middleware 사용
  apps/user/src/middleware.ts
Labels: hotfix

#196 [HOTFIX] UBLE-162 로그인 후 /map만 접속 가능한 현상 수정
  apps/user/src/middleware.ts
Labels: hotfix

#200 [FEAT] UBLE-151 UI/UX 개선 및 지도 script 로드 변경
  apps/user/src/app/(main)/home/components/AgeSection.tsx
  apps/user/src/app/(main)/home/components/PersonalSection.tsx
  apps/user/src/app/(main)/home/components/TimeSection.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/app/(no-layout)/components/KakaoLoginBtn.tsx
  apps/user/src/app/(no-layout)/page.tsx
  apps/user/src/components/MapInitializer.tsx
  apps/user/src/components/common/Header.tsx
  apps/user/src/components/ui/SectionHeader.tsx
  apps/user/src/types/constants.ts
Labels: bug, enhancement, FE

#202 [FEAT] UBLE-164 benefitCategory에 따른 제휴처 필터링 추가
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/app/(main)/home/components/ui/BenefitCategorySelector.tsx
  apps/user/src/types/brand.ts
Labels: enhancement, FE

#206 [FIX] UBLE-169 잘못된 이미지 경로 수정
  apps/user/src/app/(no-layout)/intro/page.tsx
Labels: bug

#209 [FEAT] UBLE-170 admin 대시보드 마크업
  apps/admin/src/app/(content)/dashboard/components/ChartSection.tsx
  apps/admin/src/app/(content)/dashboard/components/DashboardContainer.tsx
  apps/admin/src/app/(content)/dashboard/components/DashboardProvider.tsx
  apps/admin/src/app/(content)/dashboard/components/SearchKeywordTable.tsx
  apps/admin/src/app/(content)/dashboard/components/StatCards.tsx
  apps/admin/src/app/(content)/dashboard/components/ui/ChartCard.tsx
  apps/admin/src/app/(content)/dashboard/components/ui/StatCard.tsx
  apps/admin/src/app/(content)/dashboard/page.tsx
  apps/admin/src/components/Header.tsx
  apps/admin/src/components/Sidebar.tsx
  apps/admin/src/middleware.ts
  apps/admin/src/types/dashboard.ts
  apps/user/public/intro/search.gif
  apps/user/src/app/(no-layout)/page.tsx
Labels: enhancement, FE, admin

#210 [STYLE] UBLE-170 로그인 페이지 레이아웃 비율 변경
  apps/user/src/app/(no-layout)/page.tsx
Labels: enhancement, FE

#219 [FEAT] UBLE-178 카테고리 배치 변경
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/hooks/map/useHydrateCategories.ts
Labels: enhancement, FE

#220 [FIX] UBLE-176 현지도 검색 버튼 로직 수정 및 매장 상세 카드 변경
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/map/components/StoreDetailDrawer.tsx
  apps/user/src/app/(main)/map/hooks/useMapEffects.ts
  apps/user/src/app/(main)/map/hooks/useMapHandlers.ts
  apps/user/src/app/(main)/map/hooks/useMarkerAndClusterManager.ts
Labels: bug, FE

#225 [FIX] UBLE-181 사용 내역 페이지 가드 분기
  apps/user/src/app/(main)/mypage/history/components/BenefitList.tsx
Labels: bug, enhancement, FE

#230 [HOTFIX] UBLE-182 barcodeContainer props 변경
  apps/user/src/app/(main)/home/components/BarcodeDrawer.tsx
  apps/user/src/components/ui/BarcodeContainer.tsx
Labels: hotfix

#236 [REFACTOR] UBLE-187 지도 리팩토링
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/hooks/useMapEventHandlers.ts
  apps/user/src/app/(main)/map/hooks/useMapHandlers.ts
  apps/user/src/app/(main)/map/hooks/useMapInitialization.ts
  apps/user/src/app/(main)/map/hooks/useMapMovement.ts
  apps/user/src/app/(main)/map/hooks/useMarkerAndClusterManager.ts
  apps/user/src/app/(main)/map/hooks/useSearchLogic.ts
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/hooks/map/useCurrentLocation.ts
  apps/user/src/utils/fetchStorePins.ts
Labels: enhancement, FE

#240 [FEAT] UBLE-187 관리자 페이지 UX 향상
  apps/admin/public/profileImg.png
  apps/admin/src/app/(content)/dashboard/components/ChartSection.tsx
  apps/admin/src/app/(content)/dashboard/components/ui/EmptyChartState.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackContainer.tsx
  apps/admin/src/components/LoginPage.tsx
  apps/admin/src/components/Sidebar.tsx
  apps/admin/src/components/providers.tsx
Labels: FE, admin

#242 [HOTFIX] UBLE-189 TmpCheck 쿠키를 가지고 있는 사용자는 반드시 /signup으로 redirect
  apps/user/src/middleware.ts
Labels: hotfix

#244 [STYLE] 스타일 통일 및 실시간 검색어 기준 시각 정각으로 변경
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/page.tsx
  apps/user/src/app/(main)/search/components/TrendingSearchesSection.tsx
Labels: enhancement, FE

#247 [FEAT] UBLE-192 로그인, 로그아웃, 회원 탈퇴 시 히스토리 스택 삭제
  apps/user/src/app/(main)/mypage/components/LogoutBtn.tsx
  apps/user/src/app/(main)/mypage/components/WithdrawBtn.tsx
  apps/user/src/app/(no-layout)/kakaocallback/page.tsx
Labels: enhancement, FE

#250 [DOCS] README 업데이트 (#249)
  README.md
  diagrams/Admin_Flow.png
  diagrams/Service_Flow.png
  diagrams/information_architecture.png
Labels: deploy
