Repository MapChillE/uble-fe, pull requests merged in 2025-07, with the labels that each got.

#4 Feature/uble 22 card list
  packages/ui/eslint.config.mjs
  packages/ui/src/card.js
  packages/ui/src/components/badge.js
  packages/ui/src/components/button.js
  packages/ui/src/components/card.tsx
  packages/ui/src/gradient.js
  packages/ui/src/lib/utils.js
  packages/ui/src/turborepo-logo.js
Labels: bug, FE

#10 [FEAT] UBLE-22 페이지별 공통 list header, Card 컴포넌트 생성
  README.md
  apps/storybook/.storybook/main.ts
  apps/storybook/public/favicon.ico
  apps/storybook/src/stories/DynamicCard.stories.ts
  apps/storybook/tsconfig.json
  apps/user/package.json
  apps/user/public/placeholder.svg
  apps/user/src/app/home/components/AgeSection.tsx
  apps/user/src/app/home/components/EntireSection.tsx
  apps/user/src/app/home/components/PersonalSection.tsx
  apps/user/src/app/home/components/TimeSection.tsx
  apps/user/src/app/home/components/ui/MembershipGrade.tsx
  apps/user/src/app/home/page.tsx
  apps/user/src/app/mypage/components/FeedbackBtn.tsx
  apps/user/src/app/mypage/components/LogoutBtn.tsx
  apps/user/src/app/mypage/components/ProfileInfo.tsx
  apps/user/src/app/mypage/components/ProfileStatistics.tsx
  apps/user/src/app/mypage/components/WithdrawBtn.tsx
  apps/user/src/app/mypage/components/ui/ProfileCard.tsx
  apps/user/src/app/mypage/history/components/ui/BenefitCard.tsx
  apps/user/src/app/mypage/history/page.tsx
  apps/user/src/app/mypage/page.tsx
  apps/user/src/components/FavoriteBtn.tsx
  apps/user/src/components/ui/DynamicCard.tsx
  apps/user/src/components/ui/SectionHeader.tsx
  apps/user/src/types/api.ts
  apps/user/src/types/brand.ts
  apps/user/src/types/constants.ts
  apps/user/src/types/profile.ts
  apps/user/tsconfig.json
  packages/ui/src/components/card.tsx
  packages/ui/src/lib/utils.js
  pnpm-lock.yaml
Labels: enhancement, FE

#17 UBLE-37 feat: 로그인 페이지 UI, 카카오 로그인 버튼 추가
  apps/user/public/kakao_login.png
  apps/user/public/uble_character.svg
  apps/user/src/app/(no-layout)/components/KakaoLoginBtn.tsx
  apps/user/src/app/(no-layout)/page.tsx
Labels: enhancement, FE

#23 [FEAT] UBLE-39 사용자 추가 정보 입력 페이지 마크업
  apps/admin/package.json
  apps/storybook/package.json
  apps/storybook/src/stories/DynamicCard.stories.ts
  apps/user/package.json
  apps/user/src/app/(main)/home/components/AgeSection.tsx
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/app/(main)/home/components/PersonalSection.tsx
  apps/user/src/app/(main)/home/components/SearchSection.tsx
  apps/user/src/app/(main)/home/components/TimeSection.tsx
  apps/user/src/app/(main)/home/components/ui/MembershipGrade.tsx
  apps/user/src/app/(main)/home/page.tsx
  apps/user/src/app/(main)/mypage/components/BenefitListBtn.tsx
  apps/user/src/app/(main)/mypage/components/FeedbackBtn.tsx
  apps/user/src/app/(main)/mypage/components/LogoutBtn.tsx
  apps/user/src/app/(main)/mypage/components/ProfileInfo.tsx
  apps/user/src/app/(main)/mypage/components/ProfileStatistics.tsx
  apps/user/src/app/(main)/mypage/components/WithdrawBtn.tsx
  apps/user/src/app/(main)/mypage/components/ui/ProfileCard.tsx
  apps/user/src/app/(main)/mypage/history/components/BenefitList.tsx
  apps/user/src/app/(main)/mypage/history/components/BenefitListItem.tsx
  apps/user/src/app/(main)/mypage/history/components/BenefitStatistics.tsx
  apps/user/src/app/(main)/mypage/history/components/PeriodFilter.tsx
  apps/user/src/app/(main)/mypage/history/components/ui/BenefitCard.tsx
  apps/user/src/app/(main)/mypage/history/page.tsx
  apps/user/src/app/(main)/mypage/page.tsx
  apps/user/src/app/(no-layout)/components/KakaoLoginBtn.tsx
  apps/user/src/app/(no-layout)/kakaocallback/page.tsx
  apps/user/src/app/(no-layout)/signup/components/InputBarcodeNumber.tsx
  apps/user/src/app/(no-layout)/signup/components/InputBirth.tsx
  apps/user/src/app/(no-layout)/signup/components/NextStepBtn.tsx
  apps/user/src/app/(no-layout)/signup/components/ProgressHeader.tsx
  apps/user/src/app/(no-layout)/signup/components/SelectCategory.tsx
  apps/user/src/app/(no-layout)/signup/components/SelectGender.tsx
  apps/user/src/app/(no-layout)/signup/components/SelectMembership.tsx
  apps/user/src/app/(no-layout)/signup/components/SignupContainer.tsx
  apps/user/src/app/(no-layout)/signup/components/TestBtn.tsx
  apps/user/src/app/(no-layout)/signup/page.tsx
  apps/user/src/components/FavoriteBtn.tsx
  apps/user/src/components/ui/DynamicCard.tsx
  apps/user/src/components/ui/SectionHeader.tsx
  apps/user/src/types/constants.ts
  apps/user/src/types/profile.ts
  pnpm-lock.yaml
Labels: enhancement, FE

#37 [HOTFIX] import문 주석처리
  apps/user/src/app/(main)/map/components/MapContainer.tsx
Labels: hotfix

#40 [HOTFIX] UBLE-45 useSearchParams 훅을 사용하기 위해 Suspense로 감쌈
  apps/user/src/app/(no-layout)/kakaocallback/page.tsx
Labels: hotfix

#45 [FEAT] UBLE-47 매장 상세 정보 마크업
  apps/user/package.json
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/map/components/StoreDetailSheet.tsx
  apps/user/src/app/(no-layout)/signup/components/SelectMembership.tsx
  apps/user/src/types/constants.ts
  apps/user/src/types/store.ts
  packages/ui/src/styles/globals.css
  pnpm-lock.yaml
Labels: enhancement, FE

#49 [FEAT] UBLE-51 사용자 정보 전역 관리
  apps/user/src/app/(main)/layout.tsx
  apps/user/src/components/HydrateData.tsx
Labels: enhancement, FE

#50 [FEAT] UBLE-50 제휴처 매장 상세 정보 API 연동 및 내 장소 마크업
  apps/user/.gitignore
  apps/user/next.config.mjs
  apps/user/src/app/(main)/home/components/ui/MembershipGrade.tsx
  apps/user/src/app/(main)/map/components/CurrentLocationCard.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/MyPlaceCard.tsx
  apps/user/src/app/(main)/map/components/MyPlaceDrawer.tsx
  apps/user/src/app/(main)/map/components/MyPlaceForm.tsx
  apps/user/src/app/(main)/map/components/MyPlaceList.tsx
  apps/user/src/app/(main)/map/components/MyPlaceTriggerBtn.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/map/components/StoreDetailDrawer.tsx
  apps/user/src/app/(main)/map/components/StoreDetailSheet.tsx
  apps/user/src/hooks/map/useBaseLocation.ts
  apps/user/src/hooks/map/useNaverServiceReady.ts
  apps/user/src/hooks/map/useStorePins.ts
  apps/user/src/service/store.ts
  apps/user/src/types/map.ts
  apps/user/src/types/store.ts
  packages/ui/src/components/button.tsx
Labels: enhancement, FE

#55 [FEAT] UBLE-55 사용자 피드백 전송 기능 구현
  apps/user/src/components/modal/FeedbackModal.tsx
  apps/user/src/service/user.ts
  apps/user/src/types/profile.ts
Labels: enhancement, FE

#59 [FEAT] UBLE-57 제휴처 상세 페이지 마크업
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/app/(main)/home/components/PersonalSection.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipBenefitList.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipContainer.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipHeader.tsx
  apps/user/src/app/(main)/partnerships/[id]/page.tsx
  apps/user/src/components/FavoriteBtn.tsx
  apps/user/src/components/ui/DynamicCard.tsx
  apps/user/src/types/brand.ts
Labels: enhancement, FE

#62 [FEAT] UBLE-59 제휴처 상세 페이지 구현
  .vscode/settings.json
  apps/user/src/app/(main)/home/components/EntireSectionProvider.tsx
  apps/user/src/app/(main)/home/page.tsx
  apps/user/src/app/(main)/layout.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipBenefitList.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipContainer.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipHeader.tsx
  apps/user/src/app/(main)/partnerships/[id]/page.tsx
  apps/user/src/app/(main)/providers.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/app/not-found.tsx
  apps/user/src/service/brand.ts
  packages/ui/package.json
  packages/ui/src/components/collapsible.tsx
  pnpm-lock.yaml
Labels: enhancement, FE

#68 [FEAT] UBLE-70 사용자 위치 및 카테고리 정보 전역 저장 로직 구현
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/components/HydrateData.tsx
  apps/user/src/hooks/map/useHydrateCategories.ts
  apps/user/src/hooks/map/useHydrateLocation.ts
  apps/user/src/lib/.gitkeep
  apps/user/src/store/useCategoryStore.ts
Labels: enhancement, FE

#72 [FEAT] UBLE-71 사용자 제휴처 이용 여부 등록
  apps/user/package.json
  apps/user/src/app/(main)/map/components/BarcodeBlur.tsx
  apps/user/src/app/(main)/map/components/BarcodeContainer.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipContainer.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/Header.tsx
  apps/user/src/components/modal/BenefitConfirmModal.tsx
  apps/user/src/service/usage.ts
  apps/user/src/store/useBenefitConfirmModalStore.ts
  apps/user/src/types/usage.ts
  packages/api/src/apiHandler.ts
  pnpm-lock.yaml
Labels: enhancement, FE

#82 [FEAT] UBLE-54 마커 클러스터링 및 카테고리별 마커 스타일 설정
  apps/user/public/MarkerClustering.js
  apps/user/src/app/(main)/map/components/MyPlaceDrawer.tsx
  apps/user/src/app/(main)/map/components/MyPlaceList.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/hooks/map/useHydrateCategories.ts
  apps/user/src/types/markerClustering.d.ts
Labels: enhancement, FE

#88 [FIX] UBLE-88 지도 카테고리별 api 요청 타입 설정
  apps/user/src/hooks/map/useStorePins.ts
Labels: bug, FE

#91 [FEAT] UBLE-89 나이대 추천 제휴처 구현, DynamicCard 리팩토링
  apps/user/src/app/(main)/home/components/AgeSection.tsx
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/app/(main)/home/components/SectionError.tsx
  apps/user/src/app/(main)/home/components/SectionSkeleton.tsx
  apps/user/src/components/ui/DynamicCard.tsx
  apps/user/src/components/ui/SectionHeader.tsx
  apps/user/src/service/brand.ts
  apps/user/src/types/brand.ts
  apps/user/src/utils/scroll.ts
Labels: enhancement, FE

#92 [FEAT] UBLE-87 제휴처 검색 및 자동완성 기능 구현
  apps/user/package.json
  apps/user/src/app/(main)/home/components/HomeContent.tsx
  apps/user/src/app/(main)/home/components/SearchResults.tsx
  apps/user/src/app/(main)/home/components/SearchSection.tsx
  apps/user/src/app/(main)/home/page.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/map/components/StoreDetailDrawer.tsx
  apps/user/src/components/common/AutoCompleteInput.tsx
  apps/user/src/components/common/SearchInput.tsx
  apps/user/src/service/brandSearch.ts
  apps/user/src/types/search.ts
  pnpm-lock.yaml
Labels: enhancement, FE

#101 [FIX] UBLE-97 비정상 값 참조로 인한 hydrate error 해결
  apps/user/src/app/(main)/favorites/components/FavoriteBrandSection.tsx
  apps/user/src/app/(main)/home/components/PersonalSection.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/mypage/components/LogoutBtn.tsx
  apps/user/src/app/(main)/mypage/components/ProfileInfo.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipContainer.tsx
  apps/user/src/app/(no-layout)/kakaocallback/page.tsx
  apps/user/src/app/(no-layout)/signup/components/NextStepBtn.tsx
  apps/user/src/components/HydrateData.tsx
  apps/user/src/components/common/UserBarcode.tsx
  apps/user/src/components/modal/ProfileEditModal.tsx
  apps/user/src/components/ui/BarcodeContainer.tsx
  apps/user/src/store/useUserStore.ts
Labels: bug, enhancement, FE

#103 [FEAT] UBLE-99 지도 bounds 기반 매장 조회 로직 반영 및 유틸 분리
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/service/store.ts
  apps/user/src/utils/fetchStorePins.ts
  apps/user/src/utils/mapBounds.ts
Labels: enhancement, FE

#108 [FIX] UBLE-100 즐겨찾기 동기화
  apps/user/src/app/(main)/favorites/components/FavoriteBrandSection.tsx
  apps/user/src/app/(main)/home/components/EntireSection.tsx
  apps/user/src/components/FavoriteBtn.tsx
  apps/user/src/components/common/Footer.tsx
Labels: bug, enhancement, FE

#109 [FEAT] UBLE-102 홈화면 추천 매장 클릭시 지도 페이지 이동
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/MapSearchSection.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/MyPlaceCard.tsx
  apps/user/src/app/(main)/map/components/MyPlaceDrawer.tsx
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/store/useLocationStore.ts
  apps/user/src/store/useMapStore.ts
  packages/ui/src/components/dialog.tsx
Labels: enhancement, FE

#112 [FEAT] UBLE-82 지도 검색 구현
  apps/user/src/app/(main)/search/components/SearchContainer.tsx
  apps/user/src/app/(main)/search/layout.tsx
  apps/user/src/app/(main)/search/page.tsx
  apps/user/src/service/mapSearch.ts
  apps/user/src/service/store.ts
Labels: enhancement, FE

#114 [FIX] UBLE-100 제휴처 매장 페이지 즐겨찾기 동기화
  apps/user/src/components/FavoriteBtn.tsx
Labels: bug

#118 [FEAT] UBLE-109 마이페이지 프로필, 제휴처 안내 UI 변경, 버그 수정
  apps/user/public/profileImg.png
  apps/user/src/app/(main)/mypage/components/ProfileInfo.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipBenefitList.tsx
  apps/user/src/app/(main)/partnerships/[id]/components/PartnershipContainer.tsx
Labels: bug, enhancement, FE

#119 [FEAT] UBLE-110 매장 검색 요청 파라미터 추가 적용
  apps/user/src/app/(main)/map/components/MapSearchSection.tsx
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/app/(main)/search/components/SearchContainer.tsx
  apps/user/src/service/store.ts
  apps/user/src/utils/fetchStorePins.ts
Labels: enhancement, FE

#122 [FEAT] UBLE-112 다크모드 강제 비활성화
  apps/admin/src/components/providers.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/providers.tsx
  packages/ui/src/styles/globals.css
Labels: enhancement, FE

#124 [FEAT] UBLE-113 PWA 적용
  apps/user/.gitignore
  apps/user/next.config.mjs
  apps/user/package.json
  apps/user/public/icons/app_icon_512.png
  apps/user/public/icons/favicon.ico
  apps/user/public/icons/icon-192.png
  apps/user/public/icons/icon-512.png
  apps/user/public/manifest.json
  apps/user/src/app/ServiceWorkerRegister.tsx
  apps/user/src/app/layout.tsx
  pnpm-lock.yaml
Labels: enhancement, FE

#126 [FEAT] UBLE-115 hotjar script 추가
  apps/user/src/app/layout.tsx
Labels: enhancement, FE

#128 [FEAT] UBLE-116 카페 카테고리 추가, layout 변경 및 문구 수정
  apps/user/src/app/(no-layout)/signup/components/SelectCategory.tsx
  apps/user/src/components/modal/ProfileEditModalContents/CategorySelector.tsx
  apps/user/src/types/constants.ts
Labels: enhancement, FE

#130 [FEAT] UBLE-117 브라우저별 viewport 지정
  apps/storybook/src/pages/index.tsx
  apps/user/src/app/(main)/favorites/page.tsx
  apps/user/src/app/(main)/home/components/HomeContent.tsx
  apps/user/src/app/(main)/home/components/SearchResults.tsx
  apps/user/src/app/(main)/layout.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/mypage/history/page.tsx
  apps/user/src/app/(main)/mypage/page.tsx
  apps/user/src/app/(no-layout)/signup/components/SignupContainer.tsx
  apps/user/src/app/PreventMobileZoom.tsx
  apps/user/src/app/layout.tsx
  packages/ui/src/styles/globals.css
Labels: enhancement, FE

#138 [FIX] UBLE-125 바텀탭, 스크롤바 none 롤백
  apps/user/src/app/(main)/layout.tsx
  apps/user/src/components/common/CategoryBar.tsx
Labels: bug

#143 [FEAT] 카테고리별 아이콘 추가, 마커 클러스터링 설정 및 커스텀
  apps/user/src/app/(main)/home/components/SearchSection.tsx
  apps/user/src/app/(main)/map/components/CurrentPlaceBtn.tsx
  apps/user/src/app/(main)/map/components/MapContainer.tsx
  apps/user/src/app/(main)/map/components/NaverMap.tsx
  apps/user/src/app/(main)/search/components/SearchContainer.tsx
  apps/user/src/components/common/AutoCompleteInput.tsx
  apps/user/src/components/common/CategoryBar.tsx
  apps/user/src/components/user/DatePickerPopover.tsx
  apps/user/src/constants/categoryMarkerStyle.tsx
  apps/user/src/types/constants.ts
  apps/user/src/utils/fetchStorePins.ts
  apps/user/src/utils/mapBounds.ts
Labels: bug, enhancement, FE

#150 [FIX] UBLE-132 홈 검색 결과 하단 바텀내비 가려짐
  apps/user/src/app/(main)/home/page.tsx
Labels: bug, FE

#149 [FEAT] UBLE-131 Admin 페이지 사이드바 마크업
  apps/admin/src/app/ClientLayout.tsx
  apps/admin/src/app/feedback/page.tsx
  apps/admin/src/app/layout.tsx
  apps/admin/src/app/page.tsx
  apps/admin/src/app/statistics/page.tsx
  apps/admin/src/components/Header.tsx
  apps/admin/src/components/Sidebar.tsx
  packages/ui/package.json
  packages/ui/src/components/avatar.tsx
  pnpm-lock.yaml
Labels: enhancement, FE, admin

#156 [FEAT] UBLE-135 검색 로그 API 연동
  apps/user/src/app/(main)/home/components/SearchResults.tsx
  apps/user/src/app/(main)/home/components/SearchSection.tsx
  apps/user/src/app/(main)/search/components/SearchContainer.tsx
  apps/user/src/components/common/AutoCompleteInput.tsx
  apps/user/src/service/mapSearch.ts
Labels: enhancement, FE

#158 [STYLE] 마커 스타일 및 프로필 이미지 변경
  apps/user/public/profile.png
  apps/user/src/app/(main)/map/components/MapWithBaseLocation.tsx
  apps/user/src/app/(main)/map/components/StoreCard.tsx
  apps/user/src/app/(main)/mypage/components/ProfileInfo.tsx
  apps/user/src/utils/fetchStorePins.ts
Labels: enhancement, FE

#157 [FEAT] UBLE-136 관리자 통계 페이지 마크업
  apps/admin/package.json
  apps/admin/src/app/(content)/statistics/components/ChartSelector.tsx
  apps/admin/src/app/(content)/statistics/components/RenderChart.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsChartContainer.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsContainer.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsFilter.tsx
  apps/admin/src/app/(content)/statistics/page.tsx
  apps/admin/src/types/constants.ts
  apps/admin/src/types/statistics.ts
  packages/ui/package.json
  packages/ui/src/components/select.tsx
  pnpm-lock.yaml
Labels: enhancement, FE, admin

#162 [FEAT] UBLE-140 피드백 열람 페이지 마크업
  apps/admin/src/app/(content)/feedback/components/FeedbackContainer.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackDetailDialog.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackList.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackListItem.tsx
  apps/admin/src/app/(content)/feedback/components/FeedbackStatistics.tsx
  apps/admin/src/app/(content)/feedback/components/Pagination.tsx
  apps/admin/src/app/(content)/feedback/page.tsx
  apps/admin/src/app/(content)/statistics/components/StatisticsChartContainer.tsx
  apps/admin/src/types/feedback.ts
  apps/admin/src/utils/feedbackUtil.ts
Labels: enhancement, FE, admin

#164 [STYLE] UBLE-142 bottom tab 높이를 55px로 맞춤
  apps/user/src/app/(main)/layout.tsx
  apps/user/src/app/(main)/map/layout.tsx
  apps/user/src/components/common/Footer.tsx
Labels: enhancement, FE
